'use strict';
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { Tray, Menu, nativeImage } = require('electron');
// The tray icon ships as base64 ICO (generated by test/generate-icons.js):
// Electron 44's nativeImage fails to decode PNGs on some Windows systems,
// but always decodes ICO. The buffer is materialized to a temp .ico file —
// the only representation Electron reliably decodes here.
const { trayIco } = require('./tray-icons');

let tray = null;

function buildTrayIcon() {
  // Last-resort fallback that needs NO codec: a solid accent square built
  // from raw BGRA pixels (nativeImage.createFromBitmap never fails).
  const solid = () => {
    const w = 16, h = 16;
    const buf = Buffer.alloc(w * h * 4);
    for (let i = 0; i < buf.length; i += 4) {
      buf[i] = 0x7c; buf[i + 1] = 0x6c; buf[i + 2] = 0xff; buf[i + 3] = 0xff;
    }
    return nativeImage.createFromBuffer(buf, { width: w, height: h });
  };
  try {
    const buf = Buffer.from(trayIco.split(',')[1], 'base64');
    const file = path.join(os.tmpdir(), 'ydp-tray.ico');
    fs.writeFileSync(file, buf);
    let img = nativeImage.createFromPath(file);
    if (img.isEmpty()) img = nativeImage.createFromPath(path.join(__dirname, '..', 'assets', 'icon.ico'));
    if (img.isEmpty()) img = solid();
    return img;
  } catch {
    return solid();
  }
}

function createTray({ onShow, onToggle, onQuit, i18n }) {
  try {
    const icon = buildTrayIcon();
    tray = new Tray(icon);
  } catch (e) {
    // A broken tray must never take the whole app down (black window).
    console.error('tray disabled:', e.message);
    return null;
  }
  trayHandlers = { onShow, onToggle, onQuit };
  tray.setToolTip('YoutubeDiscordPanel');
  setTrayI18n(i18n);
  tray.on('click', () => onShow?.());
  return tray;
}

let trayHandlers = {};

// Rebuild the context menu (e.g. after the user switches UI language)
function setTrayI18n(i18n) {
  if (!tray) return;
  const t = i18n || { trayShow: 'Show', trayToggle: 'Toggle', trayQuit: 'Quit' };
  const menu = Menu.buildFromTemplate([
    { label: t.trayShow, click: () => trayHandlers.onShow?.() },
    { label: t.trayToggle, click: () => trayHandlers.onToggle?.() },
    { type: 'separator' },
    { label: t.trayQuit, click: () => trayHandlers.onQuit?.() },
  ]);
  tray.setContextMenu(menu);
}

function setTrayStatus(running) {
  if (tray) tray.setToolTip(`YoutubeDiscordPanel — ${running ? 'ON' : 'OFF'}`);
}

function destroyTray() {
  if (tray) {
    tray.destroy();
    tray = null;
  }
}

module.exports = { createTray, setTrayStatus, setTrayI18n, destroyTray };
