'use strict';
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { Tray, Menu, nativeImage } = require('electron');
// The tray icon ships as base64 ICO (generated by test/generate-icons.js):
// Electron 44's nativeImage fails to decode PNGs on some Windows systems,
// but always decodes ICO. The buffer is materialized to a temp .ico file —
// the only representation Electron reliably decodes here.
const { trayIco } = require('./tray-icons');

let tray = null;

function buildTrayIcon() {
  try {
    const buf = Buffer.from(trayIco.split(',')[1], 'base64');
    const file = path.join(os.tmpdir(), 'ydp-tray.ico');
    fs.writeFileSync(file, buf);
    const img = nativeImage.createFromPath(file);
    if (!img.isEmpty()) return img;
  } catch { /* fall through */ }
  // last resort: the packaged app icon (ICO)
  return nativeImage.createFromPath(path.join(__dirname, '..', 'assets', 'icon.ico'));
}

function createTray({ onShow, onToggle, onQuit, i18n }) {
  const icon = buildTrayIcon();
  tray = new Tray(icon);
  trayHandlers = { onShow, onToggle, onQuit };
  tray.setToolTip('YoutubeDiscordPanel');
  setTrayI18n(i18n);
  tray.on('click', () => onShow?.());
  return tray;
}

let trayHandlers = {};

// Rebuild the context menu (e.g. after the user switches UI language)
function setTrayI18n(i18n) {
  if (!tray) return;
  const t = i18n || { trayShow: 'Show', trayToggle: 'Toggle', trayQuit: 'Quit' };
  const menu = Menu.buildFromTemplate([
    { label: t.trayShow, click: () => trayHandlers.onShow?.() },
    { label: t.trayToggle, click: () => trayHandlers.onToggle?.() },
    { type: 'separator' },
    { label: t.trayQuit, click: () => trayHandlers.onQuit?.() },
  ]);
  tray.setContextMenu(menu);
}

function setTrayStatus(running) {
  if (tray) tray.setToolTip(`YoutubeDiscordPanel — ${running ? 'ON' : 'OFF'}`);
}

function destroyTray() {
  if (tray) {
    tray.destroy();
    tray = null;
  }
}

module.exports = { createTray, setTrayStatus, setTrayI18n, destroyTray };
