'use strict';
const { Tray, Menu, nativeImage } = require('electron');
// Icons are embedded as base64 data URLs (generated by test/generate-icons.js)
// so the tray icon never depends on file-path loading inside the packaged app.
const { tray32 } = require('./tray-icons');

let tray = null;

function createTray({ onShow, onToggle, onQuit, i18n }) {
  const icon = nativeImage.createFromDataURL(tray32);
  tray = new Tray(icon);
  trayHandlers = { onShow, onToggle, onQuit };
  tray.setToolTip('YoutubeDiscordPanel');
  setTrayI18n(i18n);
  tray.on('click', () => onShow?.());
  return tray;
}

let trayHandlers = {};

// Rebuild the context menu (e.g. after the user switches UI language)
function setTrayI18n(i18n) {
  if (!tray) return;
  const t = i18n || { trayShow: 'Show', trayToggle: 'Toggle', trayQuit: 'Quit' };
  const menu = Menu.buildFromTemplate([
    { label: t.trayShow, click: () => trayHandlers.onShow?.() },
    { label: t.trayToggle, click: () => trayHandlers.onToggle?.() },
    { type: 'separator' },
    { label: t.trayQuit, click: () => trayHandlers.onQuit?.() },
  ]);
  tray.setContextMenu(menu);
}

function setTrayStatus(running) {
  if (tray) tray.setToolTip(`YoutubeDiscordPanel — ${running ? 'ON' : 'OFF'}`);
}

function destroyTray() {
  if (tray) {
    tray.destroy();
    tray = null;
  }
}

module.exports = { createTray, setTrayStatus, setTrayI18n, destroyTray };
